export const colors = {
  pageBg: '#121212',
  cardBg: '#1E1E1E',
  textMain: '#E0E0E0',
  textSecondary: '#A0A0A0',
  borderLight: '#424242',
  buttonBg: '#1E1E1E',
  buttonBorder: '#E0E0E0',
  buttonText: '#E0E0E0',
  accent: '#FFFFFF',
  link: '#A0A0A0',
  originalBgHighlight: '#2C2C2E',
  originalTextHighlightInv: '#FFFFFF',
  originalChumbo: '#343A40',
  originalBrancoGelo: '#EDEDED',
  success: '#10B981',
  warning: '#F59E0B',
  error: '#EF4444',
};

export const mockUser = {
  nome: 'Ana Beatriz',
  tipo: 'Modelo',
  fotoPerfil: `https://placehold.co/100x100/${colors.originalChumbo.substring(1)}/FFFFFF?text=AB`,
  fotoCapa: 'https://placehold.co/600x200/1E1E1E/E0E0E0?text=Capa+Perfil',
  bio: 'Modelo comercial & editorial | SP & RJ | Apaixonada por moda consciente.',
  portfolio: [
    { id: 1, tipo: 'imagem', url: 'https://placehold.co/300x400/424242/E0E0E0?text=Portfólio+1', legenda: 'Editorial Vogue' },
    { id: 2, tipo: 'imagem', url: 'https://placehold.co/300x400/2C2C2E/E0E0E0?text=Portfólio+2', legenda: 'Campanha Verão' },
  ],
  experiencias: [
    { id: 1, nome: 'Campanha Outono/Inverno', cliente: 'Marca X', data: '2024', papel: 'Modelo Principal' },
  ],
  links: { instagram: '@anabeatrizmodelo', tiktok: '@anabeatriz', website: 'anabeatriz.com' },
};

export const mockCampaigns = [
  {
    id: 1,
    nome: "CASTING CALL IN BELO HORIZONTE",
    organizador: "Agência Top Models BH",
    localizacao: "Belo Horizonte",
    data: "AGO 23",
    fullDate: "23 de Agosto, 2025",
    tipo: "Casting",
    imagemCapa: "https://placehold.co/400x250/1E1E1E/A0A0A0?text=Evento+BH",
    descricaoCompleta: "Grande oportunidade para modelos em Belo Horizonte. Procuramos novos talentos para campanhas e desfiles. Presença marcante e atitude são essenciais.",
    requisitos: ["Gênero: Todos", "Altura mínima: 1.75m", "Disponibilidade imediata"],
    remuneracao: "A combinar",
    prazoInscricao: "20/08/2025",
  },
  {
    id: 2,
    nome: "MODEL CASTING AT SÃO PAULO FASHION WEEK",
    organizador: "SPFW Oficial",
    localizacao: "São Paulo",
    data: "OUT 05",
    fullDate: "05 de Outubro, 2025",
    tipo: "Desfile",
    imagemCapa: "https://placehold.co/400x250/1E1E1E/A0A0A0?text=SPFW+Casting",
    descricaoCompleta: "Participe da seleção de modelos para a próxima edição do São Paulo Fashion Week. Uma chance única de desfilar para grandes marcas.",
    requisitos: ["Experiência comprovada em passarela", "Portfólio atualizado", "Medidas padrão SPFW"],
    remuneracao: "Cachê padrão SPFW",
    prazoInscricao: "25/09/2025",
  },
   {
    id: 3,
    nome: "RIO DE JANEIRO CASTING SESSION",
    organizador: "Moda Rio Inc.",
    localizacao: "Rio de Janeiro",
    data: "NOV 18",
    fullDate: "18 de Novembro, 2025",
    tipo: "Editorial",
    imagemCapa: "https://placehold.co/400x250/1E1E1E/A0A0A0?text=Rio+Casting",
    descricaoCompleta: "Sessão de casting no Rio de Janeiro para editoriais de moda e campanhas de verão. Buscamos diversidade e autenticidade.",
    requisitos: ["Todos os gêneros e etnias", "Atitude e fotogenia", "Disponibilidade para shootings externos"],
    remuneracao: "R$ 1.500 - R$ 3.000",
    prazoInscricao: "10/11/2025",
  },
];

export const mockEvents = [
  {
    id: 1,
    title: 'Fashion Week Opening',
    date: '2024-03-15',
    time: '19:00',
    location: 'Grand Fashion Hall',
    description: 'Opening ceremony of the Spring Fashion Week',
  },
  {
    id: 2,
    title: 'Sustainable Fashion Workshop',
    date: '2024-03-16',
    time: '14:00',
    location: 'Innovation Center',
    description: 'Learn about sustainable practices in fashion design',
  },
]; 